// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDikpn3WJlV1pFOPAWqBo2536r9cV6h_VY',
    appId: '1:16970278870:web:c2184f17ee86b22ffb6677',
    messagingSenderId: '16970278870',
    projectId: 'jiddeeapp',
    authDomain: 'jiddeeapp.firebaseapp.com',
    storageBucket: 'jiddeeapp.firebasestorage.app',
    measurementId: 'G-274N5HC04K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAESnwk-pypvMCocLTN1K6MHXhRYGh1lgM',
    appId: '1:16970278870:android:a2cf4fe806210910fb6677',
    messagingSenderId: '16970278870',
    projectId: 'jiddeeapp',
    storageBucket: 'jiddeeapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiQkmL8SGB0HXfr8Jjxrwjia7yzau5r5k',
    appId: '1:16970278870:ios:73be3d96e093663ffb6677',
    messagingSenderId: '16970278870',
    projectId: 'jiddeeapp',
    storageBucket: 'jiddeeapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppJiddee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiQkmL8SGB0HXfr8Jjxrwjia7yzau5r5k',
    appId: '1:16970278870:ios:73be3d96e093663ffb6677',
    messagingSenderId: '16970278870',
    projectId: 'jiddeeapp',
    storageBucket: 'jiddeeapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppJiddee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDikpn3WJlV1pFOPAWqBo2536r9cV6h_VY',
    appId: '1:16970278870:web:ebde1f9f77dbd7a5fb6677',
    messagingSenderId: '16970278870',
    projectId: 'jiddeeapp',
    authDomain: 'jiddeeapp.firebaseapp.com',
    storageBucket: 'jiddeeapp.firebasestorage.app',
    measurementId: 'G-5D232FM58H',
  );
}
